### ISSUE TITLE
A small todo-list when I come back to this program

### ISSUE THREAD

**Issue by slumpsand** [slumpsand/os-nasm#6]
- [ ] use `KERNEL_SECTORS` in `boot.asm`
- [ ] rebuild on save
- [ ] I think I used `pusha` somewhere instead of `pushad`
- [ ] add `[16 bits]` to `boot.asm`
- [ ] maybe the `pusha` in `println` has some that I am not aware of (bootloader)
